-- Auto-generated seed data. Safe to re-run (uses upserts).
-- Generated by scripts/gen-seed.mts

-- ── Category tiles (home 'Shop by category') ──────────────────────────
insert into public.categories (id, name, icon_key, href, sort_order) values
  ('medicines', 'Medicines', 'pill', '/products?cat=pharmacy', 0),
  ('lab-tests', 'Lab Tests', 'flask', '/products?cat=lab-tests', 1),
  ('baby-care', 'Baby Care', 'baby', '/products?cat=baby-care', 2),
  ('women-care', 'Women Care', 'women', '/products', 3),
  ('men-care', 'Men Care', 'men', '/products', 4),
  ('skin-care', 'Skin Care', 'skin', '/products', 5),
  ('food-nutrition', 'Food & Nutrition', 'food', '/products', 6),
  ('oral-care', 'Oral Care', 'oral', '/products', 7),
  ('hair-care', 'Hair Care', 'hair', '/products', 8),
  ('diabetes', 'Diabetes', 'diabetes', '/products', 9),
  ('cold-cough-fever', 'Cold, Cough & Fever', 'cold', '/products', 10),
  ('protein-supplements', 'Protein & Supplements', 'protein', '/products?cat=wellness', 11),
  ('homeopathy', 'Homeopathy', 'homeopathy', '/products', 12),
  ('first-aid', 'First Aid', 'firstaid', '/products', 13),
  ('sexual-wellness', 'Sexual Wellness', 'sexual', '/products', 14),
  ('elderly-care', 'Elderly Care', 'elderly', '/products', 15),
  ('beauty-care', 'Beauty Care', 'beauty', '/products', 16),
  ('surgicals', 'Surgicals', 'surgicals', '/products', 17),
  ('mental-wellness', 'Mental Wellness', 'mental', '/products', 18),
  ('pet-care', 'Pet Care', 'paw', '/products?cat=pet-care', 19)
on conflict (id) do nothing;

-- ── Hero banners ──────────────────────────────────────────────────────
insert into public.banners (id, badge, title_top, title_bottom, subtitle, cta_label, cta_href, sort_order) values
  ('b1', 'Pharmaciti Pharmacy', 'Healthcare,', 'Delivered to You', 'Up to 25% off on medicines · Wholesale & retail · Free home delivery', 'Shop now', '/products', 0),
  ('b2', 'Wholesale & Retail', 'Wholesale Prices,', 'Retail Convenience', 'Buy in bulk or single packs — genuine medicines at the best rates', 'Shop deals', '/products', 1),
  ('b3', 'Lab Tests at Home', 'Lab Tests,', 'Sample at Home', 'Book diagnostic tests with free home sample collection', 'Book a test', '/products?cat=lab-tests', 2)
on conflict (id) do nothing;

-- ── Products ──────────────────────────────────────────────────────────
insert into public.products (id, name, brand, category, subcategory, pack, price, mrp, rx, tag, rating, description, highlights, tint, stock, active, sort_order) values
  ('dolo-650', 'Dolo 650 Tablet', 'Micro Labs', 'pharmacy', 'tablets', 'Strip of 15 tablets', 32, 32, false, 'Bestseller', 4.8, 'Paracetamol 650mg tablets used to reduce fever and relieve mild to moderate pain such as headache, body ache and toothache.', ARRAY['Fast fever relief', 'Trusted by doctors', 'For ages 12+']::text[], '#E6F4F1', 35, true, 0),
  ('vitamin-c-zinc', 'Limcee Vitamin C Tablets', 'Sarabhai Piramal', 'wellness', null, 'Strip of 15 tablets', 25, 25, false, 'Bestseller', 4.6, 'Chewable Vitamin C 500mg tablets that support daily immunity, fight fatigue and help keep skin healthy.', ARRAY['Boosts immunity', 'Vitamin C 500mg', 'Orange flavour']::text[], '#E3F0FB', 17, true, 1),
  ('cetirizine', 'Cetirizine 10mg', 'Ranbaxy', 'pharmacy', 'tablets', 'Strip of 10 tablets', 26, 26, false, null, 4.5, 'Antihistamine for relief from sneezing, runny nose, watery eyes and other allergy symptoms.', ARRAY['24 hr allergy relief', 'Non-drowsy', 'Once daily']::text[], '#EAF6EF', 29, true, 2),
  ('pantoprazole', 'Pantoprazole 40mg', 'Aristo Pharma', 'pharmacy', 'tablets', 'Strip of 15 tablets', 165, 165, true, null, 4.4, 'Reduces stomach acid. Used to treat acidity, heartburn and acid reflux. Prescription required.', ARRAY['Acidity relief', 'Take before food', 'Doctor advised']::text[], '#E9F1FA', 2, true, 3),
  ('cough-syrup', 'Ascoril Cough Syrup', 'Glenmark', 'pharmacy', 'syrups', 'Bottle of 50 ml', 43, 43, false, null, 4.3, 'Expectorant cough syrup that loosens mucus and relieves chesty cough and throat irritation.', ARRAY['Relieves chesty cough', 'Clears congestion', 'Soothes throat']::text[], '#E7F5F4', 34, true, 4),
  ('pain-spray', 'Relispray Pain Relief Spray', 'Midas Care', 'pharmacy', 'general', '55 g spray', 115, 115, false, null, 4.5, 'Fast-acting spray for quick relief from muscle pain, sprains and joint pain.', ARRAY['Quick absorption', 'Non-sticky', 'Cooling effect']::text[], '#EEF2FB', 18, true, 5),
  ('digene', 'Digene Antacid Tablets', 'Abbott', 'pharmacy', 'tablets', 'Strip of 15 tablets', 18, 18, false, null, 4.4, 'Chewable antacid tablets that give fast relief from acidity, gas, bloating and heartburn.', ARRAY['Fast acidity relief', 'Mint flavour', 'Anti-gas action']::text[], '#E4F3EC', 48, true, 6),
  ('combiflam', 'Combiflam Tablet', 'Sanofi', 'pharmacy', 'tablets', 'Strip of 20 tablets', 42, 42, false, null, 4.5, 'Ibuprofen and paracetamol combination for relief from pain, inflammation and fever.', ARRAY['Pain & fever relief', 'Anti-inflammatory', 'Trusted brand']::text[], '#E6F4F1', 58, true, 7),
  ('digestive-syrup', 'Digeplex Digestive Syrup', 'Shreya Life Sciences', 'pharmacy', 'syrups', 'Bottle of 100 ml', 57, 57, false, null, 4.3, 'Digestive syrup that eases indigestion, gas, bloating and loss of appetite.', ARRAY['Aids digestion', 'Relieves gas', 'Pleasant taste']::text[], '#E3F0FB', 49, true, 8),
  ('iron-tonic', 'Globiron Iron Tonic', 'Aglowmed', 'pharmacy', 'syrups', 'Bottle of 200 ml', 60, 60, false, null, 4.4, 'Iron and vitamin B-complex syrup that helps build haemoglobin and fight tiredness.', ARRAY['Builds haemoglobin', 'Fights fatigue', 'With B-complex']::text[], '#EAF6EF', 51, true, 9),
  ('antiseptic-liquid', 'Dettol Antiseptic Liquid', 'Reckitt', 'pharmacy', 'general', 'Bottle of 200 ml', 89, 159, false, null, 4.6, 'Multipurpose antiseptic liquid for first aid on cuts and wounds, and everyday hygiene.', ARRAY['Kills germs', 'First aid use', 'Multipurpose']::text[], '#E9F1FA', 17, true, 10),
  ('first-aid-kit', 'Cotton & Bandage First-Aid Kit', 'Pharmaciti Care', 'pharmacy', 'general', '1 kit', 199, 260, false, null, 4.5, 'Handy first-aid kit with cotton, gauze, adhesive bandages and antiseptic wipes.', ARRAY['Home & travel', 'Complete kit', 'Essential first aid']::text[], '#E7F5F4', 13, true, 11),
  ('vitamin-d3', 'Vitamin D3 60K Capsules', 'Macleods', 'pharmacy', 'vitamins', 'Strip of 4 capsules', 49, 49, false, null, 4.6, 'High-strength Vitamin D3 (cholecalciferol 60,000 IU) weekly capsules to correct deficiency and support bone health.', ARRAY['Weekly dose', 'Bone & immunity', 'Doctor recommended']::text[], '#EEF2FB', 28, true, 12),
  ('b-complex', 'Becosules Z Capsules', 'Pfizer', 'pharmacy', 'vitamins', 'Strip of 15 capsules', 31, 63, false, null, 4.4, 'Vitamin B-complex capsules with zinc that support energy metabolism and nerve health and help reduce tiredness.', ARRAY['Energy support', 'All B vitamins', 'Daily use']::text[], '#E4F3EC', 35, true, 13),
  ('metformin', 'Glycomet 500mg', 'USV', 'pharmacy', 'diabetes', 'Strip of 10 tablets', 17, 17, true, null, 4.5, 'First-line tablet for type 2 diabetes that helps control blood sugar levels. Prescription required.', ARRAY['Controls blood sugar', 'Take with meals', 'Doctor advised']::text[], '#E6F4F1', 7, true, 14),
  ('sugar-free-tablets', 'Sugar Free Gold Tablets', 'Zydus Cadila', 'pharmacy', 'diabetes', 'Pack of 300 tablets', 170, 170, false, null, 4.4, 'Zero-calorie sweetener tablets — a safe sugar substitute for tea, coffee and diabetic-friendly diets.', ARRAY['Zero calories', 'Diabetic friendly', '300 tablets']::text[], '#E3F0FB', 21, false, 15),
  ('volini-gel', 'Volini Pain Relief Gel', 'Ranbaxy', 'pharmacy', 'pain-relief', 'Tube of 50 g', 165, 165, false, null, 4.6, 'Fast-acting topical gel for relief from back pain, sprains, muscle pain and joint aches.', ARRAY['Deep relief', 'Non-greasy', 'Quick action']::text[], '#EAF6EF', 3, true, 16),
  ('moov-cream', 'Moov Pain Relief Cream', 'Paras', 'pharmacy', 'pain-relief', 'Tube of 25 g', 130, 130, false, null, 4.5, 'Targeted relief cream for back, neck and shoulder pain with a gentle warming effect.', ARRAY['Backache relief', 'Warming action', 'Trusted brand']::text[], '#E9F1FA', 32, true, 17),
  ('cold-relief', 'Coldarin Tablets', 'Knoll Pharma', 'pharmacy', 'cold-cough', 'Strip of 10 tablets', 14, 14, false, null, 4.3, 'Multi-symptom tablets that relieve blocked nose, headache, body ache and fever from cold and flu.', ARRAY['Multi-symptom relief', 'Fast acting', 'Day-time formula']::text[], '#E7F5F4', 30, true, 18),
  ('throat-lozenges', 'Solvin Lozenges', 'Ipca', 'pharmacy', 'cold-cough', 'Strip of 10 lozenges', 45, 66, false, null, 4.4, 'Medicated lozenges that soothe a sore throat and calm cough for on-the-go relief.', ARRAY['Soothes sore throat', 'Calms cough', 'On-the-go relief']::text[], '#EEF2FB', 48, true, 19),
  ('calamine-lotion', 'Caladryl Lotion', 'Parke-Davis', 'pharmacy', 'skin-care', 'Bottle of 100 ml', 81, 81, false, null, 4.5, 'Gentle calamine lotion that soothes skin irritation, rashes, itching and sunburn.', ARRAY['Soothes itching', 'Cooling relief', 'For sensitive skin']::text[], '#E4F3EC', 20, true, 20),
  ('antifungal-cream', 'Candid Antifungal Cream', 'Glenmark', 'pharmacy', 'skin-care', 'Tube of 50 g', 153, 153, false, null, 4.4, 'Medicated cream that treats fungal skin infections like ringworm, athlete''s foot and itching.', ARRAY['Treats fungal infection', 'Relieves itching', 'Dermatologist tested']::text[], '#E6F4F1', 4, true, 21),
  ('multivitamin', 'Revital H Capsules', 'Ranbaxy', 'wellness', null, 'Bottle of 30 capsules', 300, 300, false, null, 4.7, 'Complete daily multivitamin with essential vitamins, minerals and ginseng for everyday energy and wellbeing.', ARRAY['Daily energy', 'Vitamins & minerals', 'With ginseng']::text[], '#E3F0FB', 22, true, 22),
  ('ors-orange', 'Electral ORS (Orange)', 'FDC', 'wellness', null, 'Sachet of 21.8 g', 23, 23, false, null, 4.6, 'Oral rehydration salts to quickly restore lost fluids and electrolytes during dehydration.', ARRAY['WHO formula', 'Orange flavour', 'Rapid rehydration']::text[], '#EAF6EF', 40, true, 23),
  ('protein-powder', 'Whey Protein Powder 1kg', 'British Biologicals', 'wellness', null, '1 kg tub', 1675, 1675, false, 'Bestseller', 4.7, '24g protein per scoop to support muscle recovery and daily protein goals. Chocolate flavour.', ARRAY['24g protein', 'Added BCAAs', 'Easy to mix']::text[], '#E9F1FA', 54, true, 24),
  ('calcium-d3', 'Shelcal Calcium Tablets', 'Elder Pharma', 'wellness', null, 'Strip of 30 tablets', 99, 99, false, null, 4.5, 'Supports strong bones and joints. Vitamin D3 improves calcium absorption.', ARRAY['Bone strength', 'With D3', 'For adults']::text[], '#E7F5F4', 14, true, 25),
  ('sanitizer', 'Hand Sanitizer', 'ASV Labs', 'personal-care', null, 'Bottle of 60 ml', 70, 70, false, null, 4.4, '70% alcohol-based hand sanitizer that kills 99.9% of germs. Handy pocket-sized bottle.', ARRAY['Kills 99.9% germs', '70% alcohol', 'Pocket size']::text[], '#EEF2FB', 60, true, 26),
  ('n95-mask', 'N95 Protective Mask', 'ASV Labs', 'personal-care', null, '1 mask', 50, 50, false, null, 4.3, '5-layer N95 mask offering reliable protection against dust, pollution and germs.', ARRAY['5-layer filter', 'Snug fit', 'Lightweight']::text[], '#E4F3EC', 41, true, 27),
  ('face-wash', 'Himalaya Neem Face Wash', 'Himalaya', 'personal-care', null, 'Tube of 50 g', 27, 27, false, null, 4.4, 'Purifying neem face wash that fights acne and removes excess oil for clear skin.', ARRAY['Fights acne', 'Oil control', 'Daily use']::text[], '#E6F4F1', 6, true, 28),
  ('baby-diapers', 'Huggies Diaper Pants (M)', 'Huggies', 'baby-care', null, 'Pack of 20 pants', 105, 105, false, null, 4.6, 'Ultra-soft diaper pants with up to 12 hours of dryness and a breathable layer.', ARRAY['12 hr dryness', 'Soft & breathable', 'Wetness indicator']::text[], '#E3F0FB', 33, true, 29),
  ('baby-lotion', 'Johnson''s Baby Lotion', 'Johnson & Johnson', 'baby-care', null, 'Bottle of 200 ml', 150, 150, false, null, 4.7, 'Gentle daily lotion that keeps baby''s delicate skin soft and nourished.', ARRAY['Hypoallergenic', '24 hr moisture', 'No parabens']::text[], '#EAF6EF', 39, true, 30),
  ('pet-multivitamin', 'Pet Multivitamin Syrup', 'Pharmaciti Pet', 'pet-care', null, '200 ml bottle', 320, 399, false, 'New', 4.5, 'Tasty daily syrup for dogs and cats that supports coat, bones and overall vitality.', ARRAY['For dogs & cats', 'Shiny coat', 'Vet approved']::text[], '#E9F1FA', 30, true, 31),
  ('pet-shampoo', 'Tick & Flea Pet Shampoo', 'Pharmaciti Pet', 'pet-care', null, '250 ml bottle', 275, 350, false, 'New', 4.4, 'Gentle medicated shampoo that controls ticks and fleas while keeping the coat soft.', ARRAY['Tick & flea control', 'Soothes skin', 'Pleasant scent']::text[], '#E7F5F4', 62, false, 32),
  ('thermometer', 'Omron Digital Thermometer', 'Omron', 'devices', null, '1 unit', 200, 200, false, null, 4.6, 'Fast and accurate digital thermometer with fever alarm and flexible tip.', ARRAY['Quick reading', 'Fever alarm', 'Flexible tip']::text[], '#EEF2FB', 13, true, 33),
  ('bp-monitor', 'Omron BP Monitor (HEM-8712)', 'Omron', 'devices', null, '1 unit', 2180, 2180, false, 'Bestseller', 4.7, 'Fully automatic upper-arm BP monitor with large display and irregular heartbeat detection.', ARRAY['Clinically accurate', 'Large display', 'Easy one-touch']::text[], '#E4F3EC', 35, true, 34),
  ('glucometer', 'Accu-Chek Active Glucometer Kit', 'Roche', 'devices', null, 'Kit + 10 strips', 1199, 1199, false, null, 4.5, 'Easy-to-use blood glucose monitoring kit with test strips and lancets included.', ARRAY['5 sec result', 'Strips included', 'Tiny blood sample']::text[], '#E6F4F1', 2, true, 35),
  ('cbc-test', 'Complete Blood Count (CBC)', 'Pharmaciti Labs', 'lab-tests', null, 'Includes 24 parameters', 299, 450, false, null, 4.6, 'Free home sample collection. Reports in 12 hours. Covers haemoglobin, WBC, RBC, platelets and more.', ARRAY['Home collection', 'Report in 12 hrs', 'NABL labs']::text[], '#E3F0FB', 61, true, 36),
  ('full-body', 'Full Body Checkup (Basic)', 'Pharmaciti Labs', 'lab-tests', null, 'Includes 49 tests', 999, 2000, false, 'Popular', 4.7, 'Comprehensive health screening covering blood sugar, lipid profile, liver, kidney and thyroid.', ARRAY['49 tests', 'Free home collection', 'Doctor summary']::text[], '#EAF6EF', 44, true, 37),
  ('thyroid-profile', 'Thyroid Profile (T3 T4 TSH)', 'Pharmaciti Labs', 'lab-tests', null, 'Includes 3 tests', 399, 650, false, null, 4.5, 'Measures T3, T4 and TSH to assess thyroid function. Free home sample collection.', ARRAY['Home collection', 'Report in 24 hrs', 'Fasting not needed']::text[], '#E9F1FA', 46, true, 38),
  ('vitamin-d-test', 'Vitamin D Test', 'Pharmaciti Labs', 'lab-tests', null, 'Includes 1 test', 599, 1200, false, null, 4.6, 'Checks Vitamin D (25-OH) levels to detect deficiency. Free home sample collection.', ARRAY['Home collection', 'Report in 24 hrs', 'NABL labs']::text[], '#E7F5F4', 13, true, 39)
on conflict (id) do nothing;
